# -*- coding: utf-8 -*-
"""LAB_01_iris.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dp_eFXD2c_t1M0WcXeU4Ek6vfR990182
"""

from sklearn import datasets
iris  = datasets.load_iris()
print(iris)

import pandas as pd

df = pd.DataFrame( iris.data , columns = iris.feature_names )
print (df)

print(iris.target)

df['label'] = iris.target
print(df.head())

print(df.label.value_counts())

print(df.label.value_counts(normalize=True).round(3))

print(df.info())

df.isnull()

df.isnull().sum()

df.info()

df.describe()

print(iris.target)

df.corr()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set(rc = {'figure.figsize' : (4,3)})
sns.heatmap(df.corr())

sns.set(rc = {'figure.figsize' : (4,3)})
sns.heatmap(df.corr() , annot=True)

# remove Label from the correlation table
sns.set(rc = {'figure.figsize' : (4,3)})
sns.heatmap(df.iloc[: , : -1 ].corr())

sns.heatmap(df.iloc[: , : -1 ].corr() , annot=True )

sns.heatmap(df.iloc[: , : -1 ].corr() , annot=True  , cmap="YlGnBu")

sns.pairplot( df, hue ='label' , palette="tab10" , corner= True )

df.describe().loc[['min', 'max']]

from sklearn.preprocessing import MinMaxScaler

scaler= MinMaxScaler()

without_lbl = df.iloc[: , : -1 ]

scaled = scaler.fit_transform(without_lbl.values)
print(scaled)

sdf= pd.DataFrame(scaled , index = without_lbl.index  , columns =without_lbl.columns )

sdf.describe().loc[['min', 'max']].T

print ("PREVIOUS DATA")
print (without_lbl.head())

print("DATA NOW")
print (sdf.head())